---
kind: pipeline
name: default

steps:

# Notifacations - Start

- name: notify-discord-start-master
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "L4D2 Docker CI",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Build Started.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    branch:
    - master

- name: notify-discord-start-master-tagged
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "L4D2 Docker CI",
        "content": "__**TAGGED**__ - \"${DRONE_COMMIT_MESSAGE}\" -  Build Started.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - tag
    branch:
    - master

# Build & Push Docker Image

- name: build-push-image-master-latest
  image: plugins/docker
  settings:
    repo: lanopsdev/gameserver-l4d2
    tags: 
    - latest
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
    - push
    branch:
    - master

- name: build-push-image-master-tagged
  image: plugins/docker
  settings:
    repo: lanopsdev/gameserver-l4d2
    tags: 
    - ${DRONE_TAG}
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
    - tag
    branch:
    - master

# Notifcations - End

- name: notify-discord-test-failure
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "L4D2 Docker CI",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} Failed. Fix me please!",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    status:
    - failure

- name: notify-discord-image-pushed-master
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "L4D2 Docker CI",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} - Image has been built and pushed to Docker Hub.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    branch:
    - master
    status:
    - success

- name: notify-discord-image-pushed-master-tagged
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "L4D2 Docker CI",
        "content": "__**TAGGED**__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} - Image has been built and pushed to Docker Hub.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - tag
    status:
    - success

trigger:
  branch:
  - master
---
kind: signature
hmac: 1ab6f585dcbf998f282ed7bed44e5d1137525c5abca0b0287c86f0f9e6b7cc6a

...
